server:
  port: 8011

spring:
  application:
    name: service1 # 고유ID

eureka:
  instance:
    prefer-ip-address: true # 호스트명이 아닌 IP 주소를 대신 등록
    #컨테이너 기반의 MSA 환경에서 보통 DNS서버가 없기에 임의로 생성된 호스트 네임을 부여 받습니다. 이는 결국 생성된 호스트 네임의
    #정상적인 위치를 얻지 못할수 있기에 명확한 IP로 등록해 달라고 지정하는 것
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone : 등록할 유레카 서버의 위치를 지정합니다.
management:
  endpoints:
    web:
      exposure:
        include: "*"


#1. 디스커버리 서버 자체에 대한 설정
#
#eureka.server.*의 접두어로 시작하는 설정입니다.
#
#서버로서 어떻게 구성될지의 설정을 합니다. (* 즉 Eureka 서버의 프로퍼티 설정에 들어가는 내용입니다.)
#
#
#
#2. 클라이언트 자체에 대한 설정
#
#eureka.instance.*의 접두어로 시작하는 설정입니다.
#
#클라이언트로서 어떻게 구성될지의 설정입니다.
#
#
#
#3. 클라이언트 행위(Action) 설정
#
#eureka.client.*의 접두어로 시작하는 설정입니다.
#
#클라이언트가 연계할 유레카 서버 설정(defaultZone, register-with-eureka), 다른 서비스들의 정보를 가져오는(fetch-registry)등 행위에 대한 설정을 합니다.
#
#
